services:
  mountedgames.logic:
    image: ${DOCKER_REGISTRY-}mountedgameslogic
    build:
      context: .
      dockerfile: MountedGames.Logic/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Sigma123
    ports:
        - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
  sqlserver_log:
  sqlserver_secrets: